### ISSUE TITLE
corrupted fragment on decode

### ISSUE THREAD

**Issue by bloodeagle40234** [01org/isa-l#10]
Hello guys,

I found it seems isa-l can return corrupted data when trying decode from encoded data. In my experiment, that happens when using number of parities >= 5 and feeding a few combinations of the subset of the encoded data triggers the behavior.

For example, when trying to encode data set with 10 data and 10 parities, the encoded result seems correct. The data array includes the original data and parities are modified (calculated from the matrix).

And then, feeding the subset of the data and parities with
data[0], data[1],  data[2], data[3], data[4], data[6], data[7], parity[0], parity[2], parity[5]
the decoded data is different from original data.

My testing code is:
https://gist.github.com/bloodeagle40234/f5b5c39e93cd79136e33da8a5b50fdc7

I'm not sure if my code is correct or not but at least the subset
data[0], data[1],  data[2], data[3], data[4], data[6], data[7], parity[0], parity[2], parity[4]
returned correct data with the original.

Could you make sure if a bug exits or correct my testing code?

Thanks.

**Comment by gbtucker** [comment]
One issue is that the decode matrix is not invertable in this case.  You don't test the return value of gf_invert_matrix().  With large number of parity and Vandermonde encode matrix the decode matrix is not guaranteed to be invertable.  You could mitigate in a few ways but most simply you could change the example to gf_gen_cauchy1_matrix() or some other encode matrix instead of gf_gen_rs_matrix().

**Comment by clayg** [comment]
Well spotted!  But I'm afraid we might need a little bit more help to suss out the right path forward?

For example, I don't think we are perhaps the only example of code that fails to handle this seemingly rare corner case correctly.  With the following trivial diff:

```
diff --git a/erasure_code/erasure_code_base_test.c b/erasure_code/erasure_code_base_test.c
index 4d85998..b07b8d0 100644
--- a/erasure_code/erasure_code_base_test.c
+++ b/erasure_code/erasure_code_base_test.c
@@ -231,7 +231,7 @@ int main(int argc, char *argv[])
        u8 *temp_ubuffs[TEST_SOURCES];
 
        printf("erasure_code_base_test: %dx%d ", TEST_SOURCES, TEST_LEN);
-       srand(TEST_SEED);
+       srand(1368);
 
        // Allocate the arrays
        for (i = 0; i < TEST_SOURCES; i++) {
@@ -262,8 +262,8 @@ int main(int argc, char *argv[])
                return -1;
        }
        // Pick a first test
-       m = 9;
-       k = 5;
+       m = 14;
+       k = 9;
        if (m > MMAX || k > KMAX)
                return -1;
 
```

the test suite seemly correctly identifies as you did the invalid matrix:

```
ubuntu@saio:/vagrant/isa-l$ make erasure_code/erasure_code_base_test.run
erasure_code/erasure_code_base_test
erasure_code_base_test: 127x8192 BAD MATRIX
Fail to gf_gen_decode_matrix
Makefile:2955: recipe for target 'erasure_code/erasure_code_base_test.run' failed
make: *** [erasure_code/erasure_code_base_test.run] Error 255
```

... but of course the test suite passes just fine for *many* other seeds?

Perhaps a diff in `erasure_code_base_test.c` that allows this `src_err_list` (`3  5  8  a  b`) to be recovered would help us understand what we need to do?

I'm unfortunately a fair bit out of my element here - I'll probably won't be able to make much head way without some example code - it's possible @bloodeagle40234 will understand what to do when he comes online later tonight - or maybe @tsg- could offer some additional guidance?

Thanks for the quick response!

**Comment by gbtucker** [comment]
The erasure_code_test.c does a simple case using a Vandermonde matrix first with small number of parity that will always invert.  This is actually a legitimate use case as some users stick to this type of encode matrix and either keep the inputs such that it always inverts (small number of max parity) or find a way to deal with cases that cannot be extracted.  To test higher number of parity I switch to a Cauchy type so I don't have to skip the uninvertable cases.  If you increase m and k for this first case you can find an unrecoverable code where errors <= m - k but this is an expected result if you are using Vandermonde matrix.  This is fundamental to the math and not particular to ISA-L EC.  ec_encode_matrix() works for any matrices even random.

**Comment by bloodeagle40234** [comment]
Thanks for quick response! Maybe such a constraint is from sort of word size or humming distance?

Anyway, at first, let me make sure the mean for "m" and "k". I used them as

k : number of data slices
m: number of parities

but looking at terasure_code_base_test.c, it looks like you used as

k: number of data slices (same with me)
m: number of total fragments (data slices and parities, different)

right? if it's true, the condition you suggested "where errors <= m - k " means that always we can hit the unrecoverable case if using read-solomon based matrix. Can we calculate the concrete constraint for the unrecoverable case? Probably I have to think of sort of code changes for switching the matrix as you suggested and if you know something on the constraint (e.g. maybe rs_vand well performed then caucy at the throughput?), could you let me know, please.

And I think, if we make the fragments with rs_vand and large parities once, probably we cannot correct the fragments via other matrix. Is it right?

**Comment by gbtucker** [comment]
Correct on the use of (m, k), m is total number of data and parity output.  Makes it easier to describe non-symmetric cases.

For concrete constraint I have only seen the lower bounds of m x k Vandermonde invertability of sub-matrices proved by exhaustive search.  Also I've seen some attempts to extend the limits by skipping rows or deviating from the usual pattern at higher row index.

**Comment by bloodeagle40234** [comment]
Thanks for the clarification. Conclude what we should do are:

- Validate gf_invert_matrix() return value which helps us to prevent creating such a corrupted decoded data
- If more parities are needed, use gf_gen_cauchy1_matrix or other handmade matrix but it still needs to confirm it can be invertable
- Once we got corrupted elements with missing the invertable validation, no way to find the fragment  as corrupted unless we know which fragments used to decode the corrupted one.

Make sense. Sounds like, my testing code bug, thanks. If you know something more on those (in particular, 3rd item is important to us because we're now on storage systems), please let me know.

Much appreciated!

**Comment by gbtucker** [comment]
On 3rd item there are some things you can do.  I don't know what limits are in your particular system but if you find your constructed decode matrix is singular by choosing k fragments out of k+ available, you might have the chance to choose a different k set from available.  That is if you haven't exhausted the power of your code (erasures < m - k).  A different set is likely invertable.

**Comment by akalin** [comment]
I noticed this issue, too, and was about to file another bug when I noticed this one. Perhaps a comment should be added to `gf_gen_rs_matrix` stating that it may lead to singular submatrices if more than 2 parity shards are used; otherwise, other people might unknowingly use it in prod.

For posterity, the smallest singular example I could find (in terms of total number of shards) was the 11 x 6 matrix:

```
[1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 1]
[1, 1, 1, 1, 1, 1]
[1, 2, 4, 8, 16, 32]
[1, 4, 16, 64, 29, 116]
[1, 8, 64, 58, 205, 38]
[1, 16, 29, 205, 76, 180]
```

with singular submatrix

```
[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 1, 0]
[1, 1, 1, 1, 1, 1]
[1, 2, 4, 8, 16, 32]
[1, 16, 29, 205, 76, 180]
```
corresponding to trying to recover data shards 0, 3, and 5 with parity shards 0, 1, and 4.

There are probably examples that use 3 or 4 parity shards, too.

**Comment by dong-liuliu** [comment]
Thank you for the feedback, akalin.
Actually, we've already added comments about invertable conditions to gf_gen_rs_matrix, and also a test case named gen_rs_matrix_limits for user to list optional rs matrix. They are going to be shown in ISA-L new release v2.19 in this or next week.
The parameters of your rs matrix 11x6 is really out of invertable condition.

Here is a paste of added comment:
For large pairs of m and k it is possible to find cases where the decode matrix
chosen from sources and parity is not invertable. Users may want to adjust
for certain pairs m and k. If m and k satisfy one of the following
inequalities, no adjustment is required:

k <= 3
k = 4, m <= 25
k = 5, m <= 10
k <= 21, m-k = 4
m - k <= 3.

m  number of rows in matrix corresponding to srcs + parity.
k  number of columns in matrix corresponding to srcs.

**Comment by akalin** [comment]
Ah, thank you, that's perfect! Out of curiosity, how did you derive those inequalities? Are they from a paper somewhere?

**Comment by dong-liuliu** [comment]
Seems there is no shortcut.
New case gen_rs_matrix_limits can help list them.

**Comment by bigfreeZhou** [comment]
this matrix is not a singular matrix, why use gf_invert_matrix function return -1.
I'm so confused.

1 0 0 0 0 0 0 0 0 0
0 1 0 0 0 0 0 0 0 0
0 0 0 0 1 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0
0 0 0 0 0 0 0 1 0 0                                         
0 0 0 0 0 0 0 0 1 0
5 10 20 40 80 160 93 186 105 210                                                                                               
17 51 85 255 28 36 108 180 193 94                       
85 73 57 228 183 230 191 198 63 252            
64 113 121 50 250 99 143 201 150 113  

@dong-liuliu

**Comment by gbtucker** [comment]
What makes you think it is not singular?  Do you have an inverse?  How did you construct?  Any combination of exchanging rows, columns or transpose of the above that I tried also return -1 which make it seem unlikely that the matrix inverse function is incorrect.

**Comment by akalin** [comment]
FWIW, I have an independent GF(256) row reducer, and inverting the above yields

```
1 0 0 0 0 0 0 0 0 0
0 1 0 0 0 0 0 0 0 0
74 138 25 242 49 198 86 91 105 26
60 47 1 225 50 140 11 111 231 114
0 0 1 0 0 0 0 0 0 0
46 214 0 50 174 240 247 148 128 87
0 0 0 1 0 0 0 0 0 0
0 0 0 0 1 0 0 0 0 0
0 0 0 0 0 1 0 0 0 0
89 114 25 32 172 187 171 161 15 62
```
for me.

**Comment by akalin** [comment]
Note that the given matrix is invertible iff

```
20 40 160 210
85 255 36 94
57 228 230 252
121 50 99 113
```

is, and the above matrix has inverse

```
86 91 105 26
11 111 231 114
247 148 128 87
171 161 15 62
```

(according to my row reducer).

**Comment by gbtucker** [comment]
When I multiply the first two I get:
  1  0  0  0  0  0  0  0  0  0
  0  1  0  0  0  0  0  0  0  0
  0  0  1  0  0  0  0  0  0  0
  0  0  0  1  0  0  0  0  0  0
  0  0  0  0  1  0  0  0  0  0
  0  0  0  0  0  1  0  0  0  0
 ee c1 3c 6a ac 1e 7f cc b9 88
 72 a0  0 4f ee 1f e2  b e9 e8
 be 6b 3c a7 56 f7 b8 a6 f1 30
 22  a  0 82 14 f6 24 60 a0 51

And the last two I get:
 7f cc b9 88
 e2  b e9 e8
 b8 a6 f1 30
 24 60 a0 51

Neither are the identity matrix.  Could it be you are operating in a different primitive field?  
(Not  one defined by x^8 + x^4 + x^3 + x^2 + 1  , or 0x1d).

**Comment by akalin** [comment]
Ah, yes, that must be it. I'm working over 0x1b, and maybe @bigfreeZhou is, too.

**Comment by bigfreeZhou** [comment]
it's my mistake, thanks for your patient. @gbtucker

**Comment by gbtucker** [comment]
Thanks @bigfreeZhou closing the issue.

**Comment by jasonkresch** [comment]
There is a way to generate a systematic encoding matrix that is guaranteed to be invertible in any case. It works as follows:

Step 1. Generate a K by K+M Vandermonde matrix
Step 2. Generate a K by K Vandermonde matrix
Step 3. Invert the K by K Vandermonde matrix generated in step 2
Step 4. Multiply the matrix generated step 1 by the inverse Vandermonde matrix created in step 3

The matrix resulting from step 4 can serve as an encoding matrix. The first K x K rows will correspond to the identity matrix. The remaining bottom M rows can serve the purposes of encoding redundancy.

For reference, this is how the matrix is generated in other Reed-Solomon libraries, such as zfec:
https://github.com/tahoe-lafs/zfec/blob/master/zfec/fec.c#L420

**Comment by GrokDarkMatter** [comment]
I see there is another explanation for ISA-L not being able to invert Vandermonde at [www.streamscale.com](http://www.streamscale.com/). Their claim is that Vandermonde is not intended to encode Reed Solomon codewords, but to decode them, and they provide references and examples, as well as "proper" Reed Solomon encoding tables. Anyone care to comment?

**Comment by jeffareid** [comment]
@jasonkresch - replacement for gf_gen_rs_matrix() that generates the matrix you describe: step 3 and 4 are combined into a single step and in place, then the in place inverted K by K matrix is replaced with the identity matrix.

https://github.com/jeffareid/misc/blob/master/ec_vnd.c

**Comment by jeffareid** [comment]
@jasonkresch   - What Plank mentions in his 2003 correction, for k data rows and p parity rows

https://web.eecs.utk.edu/~jplank/plank/papers/CS-03-504.pdf

Step 1. Generate a k+p row by k column Vandermonde matrix
Step 2. Perform Gaussian reduction on the k columns to produce a k by k identity matrix at the top.

This generates the same matrix as you describe. Example code to do this, gf_gen_vnd_matrix:

https://github.com/jeffareid/misc/blob/master/ec_vnd.c

For ec_vnd.c, no column swap is needed for gaussian reduction.
Normally gaussian reduction would check and swap columns if needed.

**Comment by jasonkresch** [comment]
Excellent work Jeff!

ISA-L ought to add this and deprecate the old one.

Jason

**Comment by GrokDarkMatter** [comment]
@jasonkresch @jeffareid You both are smart guys, I wonder if you could check my logic and see if you agree with me.

Intel botched this matrix, I think we all agree it's the wrong one. So the real question, IMHO, is which is the "right one"? What is your humble opinion regarding of all the available matrices that could be used, which is the best?

So to be clear, I'm not talking about patents, or performance, or anything other than the matrix to replace the matrix that gf_gen_rs_matrix produces. That means we are in 0x11d in gf(2^8), and there are specific values between 1 and 255 that appear in a matrix that can be used to compute a dot product, the result being the parity values.

So that's the question - what exact matrix or matrices should the Vandermonde matrix produced by gf_gen_rs_matrix be replaced with? Not code, not math, I mean the actual values that go in the matrix.

There are many to choose from. For example, you can see how to derive several here: 
 [Information Dispersal Matrices](https://github.com/GrokDarkMatter/ISA-L-PC/blob/master/MathPapers/IDM.pdf)

My opinion is that none of these matrices are suitable. Instead, I believe it should be a polynomial code, as described here:
 [Guide for Reed Solomon Codes](https://github.com/GrokDarkMatter/ISA-L-PC/blob/master/MathPapers/BaylorWork-b188a16.pdf)

I think it's important to be exact about what matrix values are, here is my suggestion for Polynomial Code Matrices:  
[Polynomial Code Values 0x11d](https://github.com/GrokDarkMatter/ISA-L-PC/blob/master/MathPapers/PolyCodeValues.pdf)

My reasoning is pretty simple. Polynomial codes take no more space and are no more difficult to derive than Erasure Codes. They are a good replacement for gf_gen_rs_matrix because they always invert, even when rows are eliminated, so they solve a big existing problem. That's an improvement over Vandermonde as an encoding matrix.

Secondarily, they're also faster because they can be implemented with an LFSR, and they provide full error correction if and only if the user wants it. This code is self-verifying and self-correcting, and the code to detect and correct errors is freely available.

So that would be my vote, what would be your vote? Would you pick from one of the approaches in the IDM paper, or a different approach, or a polynomial code? What is the best matrix, and why? Is it one matrix, or does it change for every parity count?

**Comment by jeffareid** [comment]
@GrokDarkMatter  - The inversion issue only exists with Plank's 1997 matrix. I'm not aware of any other suggested matrix that has an inversion issue (Raid encoding doesn't count, which was Plank's 1997 suggestion).  I don't know why Plank's 2003 correction was missed. I don't know why so many erasure codes chose to use original view (modified Vandermonde) based encoding. Raid6 encoding having both DP and RS rows independent of each other make sense for the most common correction which would be a single erasure on any row other than the RS row, which only requires XOR to recover. 

Depending on the evaluation points, Lagrange is the same as Plank's 2003 correction, which is implemented in gf_gen_vnd_matrix, a modified Vandermonde matrix:

https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction#Systematic_encoding_procedure:_The_message_as_an_initial_sequence_of_values

Based on my personal experience with polynomial code | LFSR dating back to 1987, I would have chosen polynomial code after proving or finding proof that there is no inversion issue.  I'm still waiting for a benchmark for RS(16,10) k = 10, p = 6 or smaller where  LFSR based encoding would be faster. The current ISA code would not take advantage of a reduced constant count. If an implementation that took advantage of reduced constant count for faster encode is created, I would use a self-reciprocal polynomial to cut the number of unique constants by half.

Both gf_gen_bch_matrix and gf_gen_vnd_matrix provide full error correction. The decoders are different but both involve a similar key equation between an error locator polynomial and syndromes.  BCH decoder could be a bit faster if it can be implemented to use fewer unique constants.

**Comment by jasonkresch** [comment]
I would take a different approach to answering this.

The purpose of ISA-L is to demonstrate how much faster their implementation
can be compared to existing implementations of well known and well used
algorithms.

Therefore, to win over and convince other individuals and companies of this
fact, I think the most valuable thing to implement would be the exact same
function, with the exact same outputs for the given inputs, as most
everyone else seems to be using. That is, the same polynomial and the same
matrix.

Anything else would result in an apples to oranges comparison, which is
useless for those evaluating the merits of ISA-L's implementation.

So I don't think ISA-L is the right place to showcasing anything novel,
unique or esoteric, even if it's faster overall than the more standardized
methods.

Jason

**Comment by jeffareid** [comment]
@jasonkresch - gf_gen_cauchy1_matrix (Plank mentions this alternative), gf_gen_vnd_matrix (Plank's 2003 correction), or gf_gen_bch_matrix (polynomial code) can all be used as is with the existing ISA-L code with no changes other than matrix generation.  As for what most everyone else is using, that would be gf_gen_vnd_matrix.

https://www.backblaze.com/blog/reed-solomon/

https://stackoverflow.com/a/59933643/3282056

**Comment by jasonkresch** [comment]
On Sat, Oct 11, 2025, 9:40 AM Jeff Reid ***@***.***> wrote:

> *jeffareid* left a comment (intel/isa-l#10)
> <https://github.com/intel/isa-l/issues/10#issuecomment-3393341016>
>
> @jasonkresch <https://github.com/jasonkresch> - gf_gen_cauchy1_matrix
> (Plank mentions this alternative), gf_gen_vnd_matrix (Plank's 2003
> correction), or gf_gen_bch_matrix (polynomial code) can all be used as is
> with the existing ISA-L code with no changes other than matrix generation.
> As for what most everyone else is using, that would be gf_gen_vnd_matrix,
> such as Backblaze:
>
> https://www.backblaze.com/blog/reed-solomon/
>
> https://stackoverflow.com/a/59933643/3282056
>

Thanks, that is what I thought. I know that matrix was what we used at
Cleversafe / IBM as well.

Other matrices can be included, but at a minimum I think ISA-L should have
matrices corresponding to what's in common use.


Jason

**Comment by jeffareid** [comment]
@jasonkresch 

This Jan 2025 survey of erasure codes, notes that there have been a lot of papers published. Table 1 includes a list of common erasure codes, but not which matrix is used. As noted above, Backblaze and Cleversafe | IBM are using Plank's 2003 correction matrix, gf_gen_vnd_matrix. Just before table 1, the article notes that for a (n,k) code, n is usually 20 or less and n-k is 3 or 4. 

https://dl.acm.org/doi/full/10.1145/3708994

Jerasure 2.0 shows copyright (c) 2014, James S. Plank and Kevin Greenan, and includes Cauchy. It is one of the options for Ceph. I don't know how popular it is these days.

**Comment by GrokDarkMatter** [comment]
Well, I admit I have a penchant for "Now New and Amazing", that's just me. But I don't think what we're discussing here is any of "Now New or Amazing", we're talking about an encoding matrix. I'm very surprised that I am the only one among us that has an actual answer with actual values, and have not sidestepped any of the questions that I posed.

I don't think that a G matrix based on a Generator Polynomial for encoding and an H matrix based on Vandermonde for decoding is "Novel, Unique or Esoteric". I think it was the backbone of the mathematics that allowed for the construction of very small circuits that were put into wide production long before computer software could be used at application speed.

It is these same recursive characteristics that made possible both the original circuits and the superior performance of ISA-L-PC. It is a compressed and minimized approach to the problem, that's why it was the first practical implementation (then) and the best practical implementation (now). That is, best as measured in performance. We are talking about a storage "acceleration" library, right?

**Comment by jeffareid** [comment]
@GrokDarkMatter  - in the case of tape drives with 2D encoding, BCH | polynomial code error correction was performed across rows and erasure code down columns. Encoding was LFSR, not matrix. Erasure decoding used variable $e$ by $e$ matrices based on the erasures which were used to multiply syndromes to generate error values. The ISA-L matrices are fixed. Encoding only uses $n-k$ rows. Decoding selects $k$ rows for inversion and uses $e$ rows to generate error values from data and parities without the need to generate syndromes.

Raid and it's pre-cursors dates back to 1986. Plank's first paper was in 1997, the correction 2003. I was working with tape drives from 1987 to 2006 so I wasn't involved with erasure codes other than being aware of Raid. I got involved with erasure codes around 2015, initially to help students at Stack Overflow | Stack Exchange.

**Comment by GrokDarkMatter** [comment]
In Galois Fields*

 In Galois fields, full of flowers
 primitive elements dance for hours
 climbing sequentially through the trees
 and shouting occasional parities
 The syndromes like ghosts in the misty damp
 feed the smoldering fires of the Berlekamp
 and high-flying exponents sometimes are downed
 on the jagged peaks of the Gilbert bound.

[NASA, August 1978](https://scispace.com/pdf/a-decoding-procedure-for-the-reed-solomon-codes-3v4td86w1p.pdf)

Let m0, d, s, and t be any positive integers, and a be an element of
 GF(qs). There exists a q-ary BCH code of length n = qs - 1 symbols that
 corrects any combination of t or fewer errors and requires no more than 2st
 parity-check symbols. Let g(X) be a polynomial of lowest degree over GF(q)
 and select q = 2m. The code generated by g(X) is a cyclic BCH code and has
 am°, am°+1, . . ., a m°+d"2 (1)
 as roots. The special q-ary BCH code, for which s = mg = 1 and d = 2t + 1,
 is called the RS code. The roots of the RS code are
 a, a2, a3, . . .,a2t (2)
 Since the minimum polynomial with root of a
 is simply (x+a ), the generator polynomial g(X) of a t-error-correcting RS code of length 2m - 1 is
 g(X) = (X+a) (X+a2) . . . (X+a2t)  (3)
 The codeword polynomials generated by g(X) consist of the multiples of
 g(X) modulo Xn + 1, and have a, a2, a3, . . . , a2t as roots. Since g(X) has
 degree 2t, and a is a primitive nth root of unity in GF(2m), the RS code
 generated by g(X) is a t-error-correcting cyclic code with the following
 parameters :
 Code length (symbols): n = 2m - 1
 Number of parity check symbols: n - k = 2t
 Minimum distance: d = 2t + 1
 Number of information symbols: k = 2 - 1 - 2

(Sorry the text cut and paste wasn't very good but you can chase the link to see for yourself)

I would suggest that this is "common use" since at least 1978, long before Plank or Anvin wrote any papers.

**Comment by jeffareid** [comment]
@GrokDarkMatter - I'm not sure about common uses, but BCH codes started in 1959|1960. Reed Solomon's 1960 MIT paper describes a method of using a message at a polynomial to generate a codeword of values. There were no practical decoders for that, but BCH already had the PGZ decoder, so a switch was made in 1960 to use BCH compatible encoding using a fixed generator polynomial with successive powers of a field primitive as roots. The very first book on Error Correcting Codes published in 1961 mentions RS codes as a sub-class of BCH codes, with no mention of the encoding scheme in the 1960 paper. So "common" use of BCH compatible RS code would date back to 1960. I don't know why two completely different encoding | decoding methods are both called Reed Solomon.

I already mentioned Raid dates back to 1986 (IBM had a version of Raid 5 before the term Raid existed).  Raid 6 was late 1980's. I don't know when generic erasure codes first started to be used.

**Comment by GrokDarkMatter** [comment]
"Plank's first paper was in 1997, the correction 2003." Proper codes, which used a G matrix based on a Generator Polynomial to encode and an H matrix based on Vandermonde to decode were well known at least twenty years earlier. And, unlike the 1997 paper, they actually worked, and did not require a subsequent retraction and correction.

I do appreciate the work that Dr. Plank did, it was brave. Completely wrong, just like Intel, as it turns out, but brave. I applaud him for daring to venture into the field, and causing this discussion. He was strong enough to correct himself (at least partially), good for him. Let's see if Intel is strong enough, as well.

**Comment by GrokDarkMatter** [comment]
@jeffareid @jasonkresch Here's a picture of how much faster it is to encode and decode with ISA-L-PC rather than the "dot product" coding scheme used in ISA-L.

"Voyager 2 was launched on August 20, 1977, and Voyager 1 launched on September 5, 1977. Both probes were equipped with a Reed-Solomon (RS) encoder to enhance their communication capabilities. The RS encoding, like with the RS(255,223), was switched on during the mission to correct errors in the transmitted data."

![ISA-L-PC Performance Graph](https://raw.githubusercontent.com/GrokDarkMatter/ISA-L-PC/master/performance.png)

**Comment by GrokDarkMatter** [comment]
Here's how to build an LFSR similar to Voyager (the G values are from the Generator Polynomial):

![Voyager LFSR](https://raw.githubusercontent.com/GrokDarkMatter/ISA-L-PC/master/LFSR.png)
