### ISSUE TITLE
NASM warning: absolute address can not be RIP-relative

### ISSUE THREAD

**Issue by ilmarmors** [01org/isa-l#16]
Lots of warning: absolute address can not be RIP-relative
when compiling with latest NASM version 2.12.02 (compiled on Jul  6 2016) on CentOS 7

**Comment by gbtucker** [comment]
This is nasm bug https://bugzilla.nasm.us/show_bug.cgi?id=3392361 and the same as issue #8 but got closed.  I suggest we keep this item open until nasm fixes this bug.

**Comment by gbtucker** [comment]
Looks like this is now fixed in nasm.  Latest nasm tip no longer gives this warning.

nasm, however, has introduced a few new unnecessary warnings:
`crc/crc_multibinary.asm:100: warning: byte data exceeds bounds`
`crc/crc_multibinary.asm:138: warning: byte data exceeds bounds`
but as before still produces the correct opcodes.

**Comment by gbtucker** [comment]
Nasm fix for this has been out for awhile.
