### ISSUE TITLE
erasure code are much slower on a mac

### ISSUE THREAD

**Issue by templexxx** [01org/isa-l#18]
on my macbook. the erasure_code_perf is not so stable. sometimes it's fast, sometimes it's so slow.
for example, 10+4(16MB per shards),it will be 2753-4434( I use 10*16MB/loops/time_cost).

on linux, it's stable and fast. 4300MB/s on a linux vm on my macbook.

all the gf_* 's performance on mac are not as good as linux. But other's performance is a little slower than mac, like crc, raid

I can't figure out why? Maybe you have some issue?

**Comment by gbtucker** [comment]
I think the performance should be much the same on Linux or Mac.  Likely the difference is due to limitations in the simple performance tests.  The included ones are meant to be rough evaluations and you may notice that with some functions, especially with the very low cycles-per-byte ones, there is a large difference between "cold" and "warm" options.  The functions you mention: crc, raid, ec are all in this category.  Small system differences could be influencing to run more like unintended warm.

**Comment by templexxx** [comment]
Yes. It should be same. The difference has nothing about these codes, thank you for your patience
