### ISSUE TITLE
bl_count[0] uninitialized ,

### ISSUE THREAD

**Issue by youngchopin** [01org/isa-l#34]
code_len_count,  bl_count[0] uninitialized in this two part
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L964-L967
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L976-L980
and use in the following line
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1487-L1490
the argument count usd the following line, and usd count[0], may cause problem
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1015-L1016

**Comment by rjoursler** [comment]
Thank you for submitting this issue, we will go ahead and fix it. This uninitialized value currently does not cause an issue because in this loop
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1015-L1016
the important bits for next_code[i] are the first i bits, which are not set by count[0]. All other bits are masked off in a call to the function bit_reverse a short while later.

**Comment by youngchopin** [comment]
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1015-L1016
in this line, when i =1,the code seen like this
` 	next_code[1] = (next_code[0] + count[0]) << 1; `
and the `count[0]` has read uninitialized 

the `count` is the third argument of function `set_huff_codes`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1487-L1490
