### ISSUE TITLE
when code, must the buffer be aligned with 64?

### ISSUE THREAD

**Issue by liuiangang** [01org/isa-l#41]

**Comment by gbtucker** [comment]
We have eliminated most of the alignment restrictions in various units but a few remain in raid functions.  The documentation will list any necessary alignment restrictions on input buffers.

**Comment by liuiangang** [comment]
In file of erasure_code_test.c, I see the example which allocate buffer align，if not align,can it work well? if not,why must be align?

**Comment by liuiangang** [comment]
In file of erasure_code_test.c, I see the example which allocate buffer align，if not align,can it work well? if not,why must be align?
![1531446016 1](https://user-images.githubusercontent.com/12525667/42667964-d2548044-8680-11e8-92a2-7350fa4b619f.jpg)

**Comment by gbtucker** [comment]
In this unit test we explicitly align so that we can explicitly test the unaligned cases also by shifting buffers up to a page border and running with efence.  Malloc will normally align anyway but this will help so that `efence_buffer = buffer + buffer_len - test_size` will push up against a page boundary and help us test against readover.  In your user code, alignment is not a requirement and it should work will without.
