### ISSUE TITLE
isal_inflate() errors with large (>4 GB uncompressed) blocks

### ISSUE THREAD

**Issue by pdexheimer** [01org/isa-l#42]
Hi -

I consistently get ISAL_INVALID_LOOKBACK results from isal_inflate() at a particular location in a large gzip.  The file inflates just fine with command line gzip, so I don't believe that the data is actually bad.  In debugging, I discovered that the error occurs after `state->total_out` passes 2^32 and rolls back over to zero.

From what I can tell, the culprit is in decode_huffman_block_stateless, where there's a check to ensure that the loopback distance doesn't exceed the value of total_out:
https://github.com/01org/isa-l/blob/7da82d555f1d25fdd4c1e7afd849ed2d9fb7ea1d/igzip/igzip_inflate.c#L1614-L1615 But since total_out has rolled over, this check is failing on valid data.

Commenting out this check and the corresponding lines in igzip_decode_block_stateless.asm: https://github.com/01org/isa-l/blob/7da82d555f1d25fdd4c1e7afd849ed2d9fb7ea1d/igzip/igzip_decode_block_stateless.asm#L587-L588
 fixed the issue for me, but I'm not sure that I understand the code well enough to be confident that there would be no further side effects

**Comment by gbtucker** [comment]
Thanks @pdexheimer, I think you got the issue.  These lines check if the decoded look-back distance is not past the beginning of the buffer (and could otherwise cause a seg fault on a faulty compressed stream).  However `state->total_out` is a `uint32_t`.  We can't just delete the lines but there is probably an easier way to deal with enormous files.  We'll look into it and get back to you.

**Comment by pdexheimer** [comment]
Thanks @gbtucker!  It looks like the fix worked for my data!
