### ISSUE TITLE
Deflate level 0 compresses data

### ISSUE THREAD

**Issue by zbjornson** [01org/isa-l#45]
In zlib, level 0 "gives no compression at all (the input data is simply copied a block at a time)." In isa-l, level 0 is close zlib's level 1 as far as compression ratios. Is this intentional?

It's straightforward to add a level 0 to my own code since it's just the data with the header and checksum, but I wanted to make sure something wasn't amiss since level 0 does appear to be special in some ways in isa-l. For example, its level buf size is 0.

Thanks! :)

**Comment by gbtucker** [comment]
Zach,
Isa-l level 0 does a static Huffman, single pass compression that should still give reasonable compression ratios but very fast.  Isa-l level 1 is fully dynamic, two pass so the compression ratios are usually better than level 0.  This was intentional.  It helps us extend the speed vs. compression ratio curve out further.  Also since you can specify your own custom hufftable for level 0, it allows a lot of flexibility. The level buf is not necessary for level 0 since it doesn't need to store symbols in an intermediate buffer between passes.
--Greg

**Comment by zbjornson** [comment]
Awesome, thanks for the fast and helpful reply! (And thanks for providing this great library.)
